# Generated by Django 4.0.5 on 2022-06-02 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='Birth_Day',
            field=models.DateField(auto_now=True),
        ),
    ]
